language: php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

matrix:
    include:
        - php: 7.1
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.3

before_install:
    - phpenv config-rm xdebug.ini
    - composer validate
    - COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit -v
    - ./vendor/bin/phpspec run -f pretty
